# available filter types:
# eq equals
# neq not equals
# gt greater than
# gte greater than or equals
# in sepatate by commas
# isnull
# lt lower than
# lte lower than or equals
# not/ne sepatate by commas
# not_in/nin
# like/ilike
apps:
- name: "User"
  table_name: "users"
  humanized_name: "Пользователи"
  table_cols:
  - name: "id"
    type: "int"
  - name: "email"
    type: "str"
  - name: "password"
    type: "str"
  - name: "middlename"
    type: "str"
  - name: "firstname"
    type: "str"
  - name: "lastname"
    type: "str"
  - name: "is_email_confirmed"
    type: "bool"
  - name: "email_confirmed_at"
    type: "datetime"
  - name: "phone"
    type: "str"
  - name: "iin"
    type: "str"
  - name: "is_active"
    type: "bool"
  - name: "is_admin"
    type: "bool"
  - name: "created_at"
    type: "datetime"
  - name: "last_seen_at"
    type: "datetime"
  - name: "id_card"
    type: "str"
  
  filters:
  - col: "email"
    types: 
    - eq
