"""add user fields

Revision ID: e6139921da5f
Revises: 69dcdfaef72b
Create Date: 2023-02-15 13:51:02.971632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6139921da5f'
down_revision = '69dcdfaef72b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_phone_confirmed', sa.Boolean(), nullable=True, default=False))
    op.add_column('users', sa.Column('phone_confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_confirmed_at')
    op.drop_column('users', 'is_phone_confirmed')
    # ### end Alembic commands ###
